services:
  fastapi:
    build: 
      context: ./fastAPI_app 
      dockerfile: dockerfile 
    container_name: fastAPI
    working_dir: /app
    ports:
      - "${PORT_FASTAPI:-8000}:8000"
    env_file:
      - .env  
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY} 
    volumes:
      - ./fastAPI_app:/app   
    networks:
      - ai_network
    restart: always


networks:
  ai_network:
    driver: bridge

volumes:
  es_data:
